INSERT INTO PHRASE(id, english, cebuano) VALUES (	1	,	'my daughter has two cats','ako anak nga babayi kay naay duha ka iring');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	2	,	'my son is a student','ako anak nga lalaki kay studyante');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	3	,	'my brother has one son','ako igsuon nga lalaki ky naay usa ka anak nga lalaki');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	4	,	'this is my house','ako ni balay');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	5	,	'my name is Maya','ako pangalan kay Maya');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	6	,	'my house is white','ang ako balay kay puti');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	7	,	'our dream is to visit Paris','ang amo damgo kay mubisita sa Paris');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	8	,	'her daughter is a student','ang iya anak nga babayi kay studyante');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	9	,	'his hobby is reading books','ang iya lingaw kay magbasa ug libro');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	10	,	'his sisters are young','ang iya mga igsuon nga babayi ky bata pa');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	11	,	'his brothers are young','ang iya mga igsuon nga lalaki ky bata pa');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	12	,	'where do you live?','asa ka nagpuyo?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	13	,	'Where is the airport?','asa man ang paluparan?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	14	,	'don''t leave me' , 'ayaw ko biya-e');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	15	,	'I don''t speak French','di ko musulti ug French');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	16	,	'their house is not far','di man layo ang ila balay');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	17	,	'we will not come late','di mi muabot nga ulhi');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	18	,	'we will not come late','Di mi muabot nga ulhi');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	19	,	'can''t she play chess?','di siya kaduwa ug chess?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	20	,	'he cannot see us','di siya kita nato');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	21	,	'this is not the correct phrase','dili ni mao nga sinultian');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	22	,	'Go straight','diretso lang');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	23	,	'I like our breakfast','ganahan ko sa amo pamahaw');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	24	,	'I want a sandwich without onions','ganahan ko ug pan nga naay palaman nga walay sibuyas');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	25	,	'they visited her yesterday','gibisita siya nila gahapon');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	26	,	'he gave them food','gihatagaan niya sila ug pagkaon');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	27	,	'did you read the third book?','ima ba gibasa ang ikatulo nga libro?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	28	,	'your brother lives here','imu igsuon nga lalaki kay nagpuyo diri');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	29	,	'your country is big','imu nasud kay dako');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	30	,	'her mother cooks for us','iya inahan kay nagluto para namo');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	31	,	'those stars are shiny','kadtong mga bituon kay sinaw');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	32	,	'that restaurant is far','kana nga kan-anan kay layo');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	33	,	'do you understand me now?','kasabot naka nako karon?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	34	,	'these apples are delicious','kini nga mga mansanas kay lami');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	35	,	'Turn right','liko sa tuo');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	36	,	'Turn left','liko sa wa');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	37	,	'This is very expensive','mahal ni kaayo');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	38	,	'does she speak Chinese?','makastorya siya ug Chinese?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	39	,	'can she help us?','makatabang ba na siya nato?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	40	,	'Can you help me?','makatabang ka nako?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	41	,	'we are happy here','malipayon mi diri');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	42	,	'they are happy now','malipayon na sila karon');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	43	,	'this is my second lesson','mao ni ako ikaduha nga leksyon');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	44	,	'he is taller than her','mas taas pa siya kaysa niya');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	45	,	'she can speak German','maskasulti siya ug German');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	46	,	'new books are expensive','mga bago nga libro kay mahal');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	47	,	'I am your friend','migo man ko nimu');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	48	,	'I eat without a knife','mukaon ko nga walay kutsilyo');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	49	,	'I speak one language','mustorya ko ug usa ka linguahe');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	50	,	'we speak three languages','mustorya mi ug tulo ka linguahe');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	51	,	'she speaks seven languages','musulti siya ug pito ka linguahe');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	52	,	'do you have milk?','naa ba kay gatas?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	53	,	'I have a small green house','naa ko''y gamay nga balay nga berde');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	54	,	'I have milk and coffee','naa ko''y gatas ug kape');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	55	,	'I have three dogs','naa ko''y tulo ka iro');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	56	,	'Is this seat taken?','naa naglingkod diri nga lingkuranan?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	57	,	'she only has one apple','naa ra siya''y usa ka mansanas');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	58	,	'she has five red shoes','naa siya''y lima ka pula nga sapatos');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	59	,	'she has a tall sister','naa siya''y taason nga igsuon nga babayi');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	60	,	'he has a tall brother','naa siya''y taason nga igsuon nga lalaki');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	61	,	'she has three small dogs','naa siya''y tulo ka gagmay nga iro');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	62	,	'he has three dogs','naa siya''y tulo ka iro');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	63	,	'he has three apples','naa siya''y tulo ka mansanas');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	64	,	'they bought milk and bread','nagpalit sila ug gatas ug pan');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	65	,	'we live in a small house','nagpuyo mi sa gamay nga balay');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	66	,	'she lives near the church','nagpuyo siya duol sa kapilya');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	67	,	'she wrote him a letter','nagsuwat siya ug suwat para niya');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	68	,	'I understand you','nakasabot ko nimu');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	69	,	'I need help immediately','nanginahanglan ko ug tabang karon dayun');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	70	,	'he came with his small dog','niabot siya uban iya gamay nga iro');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	71	,	'he visits many countries','nibisita siya ug daghang nasud');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	72	,	'I''m good. Thank You.','Okay rako. Salamat');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	73	,	'you speak very fast','paspasa man ka musulti');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	74	,	'I will always love you','pirmi tika higugmaon');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	75	,	'can you come with me?','pwede ka muuban nako? ');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	76	,	'can I help you?','Pwede ko makatabang ko nimu?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	77	,	'Can I help you?','pwede ko makatabang ko nimu?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	78	,	'can you tell me your name?','pwede ko nimu sultian sa imu pangalan?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	79	,	'can we learn German together?','pwede mag-uban ug kat-on ug German?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	80	,	'this language is very easy','sayon rajud ni nga linguahe');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	81	,	'I will give you money','tagaan tika ug kwarta');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	82	,	'how much is this?','tagpila man ni?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	83	,	'How much is this?','tagpila man ni?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	84	,	'what is your name?','unsa imu pangalan?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	85	,	'Then','unya');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	86	,	'I''m vegetarian','utan ra ako kaonon');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	87	,	'she is very intelligent','utukan siya kaayo');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	88	,	'I don''t understand you','wa ko kasabot nimu');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	89	,	'she didn''t visit Germany','wala siya nibisita sa Germany');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	90	,	'no problem','way problema');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	91	,	'how are you?','musta man ka?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	92	,	'and you?','ikaw?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	93	,	'what is your name?','unsa imu pangan?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	94	,	'my name is Maya','ako pangalan kay Maya');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	95	,	'nice to meet','you maaung pakigkita nimu');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	96	,	'Do you speak (English/ Cebuano)?','makastorya ka ug (Iningles/ cebuano)?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	97	,	'Just a little','ginagmay lang');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	98	,	'I like Cebuano','ganahan ko ug cebuano');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	99	,	'Can I practice with you?','pwede ko magpraktis kauban nimu?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	100	,	'How old are you?','pila na imu edad?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	101	,	'I''m thirty three years old','trayntay tres na ako edad');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	102	,	'It was nice talking to you','nindot kaau makigstorya nimu');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	103	,	'Help','tabang');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	104	,	'Call the ambulance','tawagi ang ambulansya');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	105	,	'I need a doctor','nanginahanglan ko ug duktor');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	106	,	'Where is the closest pharmacy?','asa man ang pinakaduol nga botika');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	107	,	'Are you okay?','okay raka?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	108	,	'I am sick','gihilantan ko');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	109	,	'Call the police','tawagi ang pulis');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	110	,	'What do you mean?','Unsay imu buot pasabot?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	111	,	'I don''t understand','Wa ko kasabot');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	112	,	'I don''t know','Wa ko kahibaw');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	113	,	'What is that called in Cebuano?','Unsay tawag ana sa cebuano?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	114	,	'What is this?','Unsa ni?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	115	,	'What does that phrase mean in English?','Unsay pasabot ana nga sinultian sa Iningles?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	116	,	'Sorry (if you made a mistake)','pasaylo');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	117	,	'Where are you from?','Asa man ka gikan?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	118	,	'I''m from the U.S','Gikan ko sa U.S');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	119	,	'I''m American','Americano ko');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	120	,	'Where do you live?','Asa ka nagpuyo?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	121	,	'I live in the U.S','Nagpuyo ko sa U.S');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	122	,	'What do you do for a living?','Unsa man imu panginabuhi?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	123	,	'I''m a student','Estudyante ko');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	124	,	'Happy birthday','malipayong kaadlawan');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	125	,	'Happy new year','Malipayong bag-ong tuig');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	126	,	'Merry Christmas','Malipayong pasko');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	127	,	'Good luck','Maayong swerte');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	128	,	'I have a reservation (hotel)','naa koy reserba');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	129	,	'Do you have rooms available?','naa pa may bakante nga kwarto?');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	130	,	'I would like a non-smoking room','Ganahan ko ug kwarto nga bawal manigarilyo');
INSERT INTO PHRASE(id, english, cebuano) VALUES (	131	,	'What is the charge per night?','Pilay bayad kada gabi-e');
