INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	1,'Alt+Shift+J','/** or Alt+Shift+S','?','create documentation');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	2,'F4','ctrl+h','?','show the type hierarchy');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	3,'ctrl+alt+g','ctrl+alt+F7','?','find usages');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	4,'ctrl+shift+u','ctrl+f7','','finds the usages in the same file');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	5,'alt+shift+r','shift+F6','','rename');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	6,'ctrl+shift+r','ctrl+shift+N','','find file / open resource');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	7,'ctrl+shift+x, j','ctrl+shift+F10','','run (java program)');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	8,'ctrl+shift+o','ctrl+alt+o','','organize imports');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	9,'ctrl+o','ctrl+F12','','show current file structure / outline');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	10,'ctrl+shift+m','ctrl+alt+V','','create local variable refactoring');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	11,'syso ctrl+space','sout ctrj+j','','System.out.println(â€œâ€)');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	12,'alt+up/down','ctrl+shift+up/down','','move lines');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	13,'ctrl+d','ctrl+y','Ctrl+shift+k','delete current line');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	14,'???','alt+h','?','show subversion history');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	15,'ctrl+h','ctrl+shift+f','','search (find in path)');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	16,'â€œsemiâ€ set in window-> preferences','ctrl+shift+enter','','if I want to add the semi-colon at the end of a statement');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	17,'ctrl+1 or ctrl+shift+l','ctrl+alt+v','','introduce local variable');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	18,'alt+shift+s','alt+insert','','generate getters / setters');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	19,'ctrl+shift+f','ctrl+alt+l','Ctrl+shift+i','format code');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	20,'ctrl+y','ctrl+shift+z','','redo');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	21,'ctrl+shift+c','ctrl+/','','comment out lines (my own IDEA shortcut definition for comment/uncomment on german keyboard layout on laptop: ctrl+shift+y)');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	22,'ctrl+alt+h','ctrl+alt+h (same!)','','show call hierarchy');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	23,'none ?','ctrl+alt+f7','','to jump to one of the callers of a method');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	24,'ctrl+shift+i','alt+f8','','evaluate expression (in debugger)');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	25,'F3','ctrl+b','','go to declaration (e.g. go to method)');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	26,'ctrl+l','ctrl+g','','go to line');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	27,'main','psvm','','create main method');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	28,'???','fori','','create for each lop');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	29,'link with editor','Autoscroll from Source','','source file you are viewing in the current tab will be highlighted and have its package expanded in the Package Explorer view.');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	30,'Ctrl+T','Ctrl+alt+b','','Navigate to Implementation');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	31,'???','Ctrl+U ','','Go to super declaration');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	32,'','f2','','next code issue');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	33,'','shift+f2','','previous code issue');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	34,'','Alt+J','Ctrl+D','Add Selection for Next Occurrence');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	35,'alt+left/right','','','Go to previously edited lass');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	36,'ctrl+shift+t','','','open type');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	37,'ctrl+e','','','list all open editors');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	38,'ctrl+i','','','correct indentation');
INSERT INTO SHORTCUT(id,eclipse, intellij, vs_code,description) values (	39,'ctrl+j','','','incremental search');
